initialization_params:
  num_of_nodes: 36
  mu: 0.05
  max_iter: 100
  mask_dis_threshold: 10
  pub_tracking_image: true
  using_rope_with_markers: true
  max_end_displacement: 0.01
  max_total_len_change: 0.015

CPD_LLE_params:
  beta: 0.2
  alpha: 1
  gamma: 1
  mu: 0.05
  max_iter: 50
  tolerance: 0.00001
  include_lle: true
  use_geodesic: true
  use_prev_sigma2: false
  sigma2_0_scale: 200
  kernel: "Gaussian"

# params_1 will be used for bounded situation
ECPD_params_1:
  beta: 2
  alpha: 1
  gamma: 1
  mu: 0
  max_iter: 30
  tolerance: 0.00001
  include_lle: true
  use_geodesic: true
  use_prev_sigma2: true
  omega: 0.000001
  kernel: "Gaussian"

# params_2 will be used for unbounded situation
ECPD_params_2:
  beta: 7
  alpha: 1
  gamma: 1
  mu: 0
  max_iter: 30
  tolerance: 0.00001
  include_lle: true
  use_geodesic: true
  use_prev_sigma2: true
  omega: 0.000001
  kernel: "1st order"